"""审计动作枚举（B5）。

用常量而不是裸字符串：这些值会进 DB 并作为前端筛选条件，写错一个字母
就会出现「查不到刚才那条记录」的静默故障。
"""

from __future__ import annotations

ACTION_LOGIN_SUCCESS = "login.success"
ACTION_LOGIN_FAILURE = "login.failure"
ACTION_USER_CREATE = "user.create"
ACTION_USER_ACTIVATE = "user.activate"
ACTION_USER_ROLE_CHANGE = "user.role_change"
ACTION_USER_DISABLE = "user.disable"
ACTION_USER_ENABLE = "user.enable"
ACTION_USER_PASSWORD_CHANGE = "user.password_change"
ACTION_USER_PASSWORD_RESET = "user.password_reset"
ACTION_USER_DELETE = "user.delete"
ACTION_CREDENTIAL_IMPORT = "credential.import"
ACTION_CREDENTIAL_DELETE = "credential.delete"
ACTION_CREDENTIAL_TOGGLE = "credential.toggle"
ACTION_CREDENTIAL_PIN = "credential.pin"
ACTION_CREDENTIAL_REVIVE = "credential.revive"
ACTION_CREDENTIAL_SWITCH_ACCOUNT = "credential.switch_account"

ACTIONS: tuple[str, ...] = (
    ACTION_LOGIN_SUCCESS, ACTION_LOGIN_FAILURE,
    ACTION_USER_CREATE, ACTION_USER_ACTIVATE, ACTION_USER_ROLE_CHANGE,
    ACTION_USER_DISABLE, ACTION_USER_ENABLE,
    ACTION_USER_PASSWORD_CHANGE, ACTION_USER_PASSWORD_RESET, ACTION_USER_DELETE,
    ACTION_CREDENTIAL_IMPORT, ACTION_CREDENTIAL_DELETE, ACTION_CREDENTIAL_TOGGLE,
    ACTION_CREDENTIAL_PIN, ACTION_CREDENTIAL_REVIVE, ACTION_CREDENTIAL_SWITCH_ACCOUNT,
)

# 界面上的中文标签（审计页筛选下拉用）
ACTION_LABELS: dict[str, str] = {
    ACTION_LOGIN_SUCCESS: "登录成功",
    ACTION_LOGIN_FAILURE: "登录失败",
    ACTION_USER_CREATE: "新建用户",
    ACTION_USER_ACTIVATE: "激活账号",
    ACTION_USER_ROLE_CHANGE: "变更角色",
    ACTION_USER_DISABLE: "禁用用户",
    ACTION_USER_ENABLE: "启用用户",
    ACTION_USER_PASSWORD_CHANGE: "修改密码",
    ACTION_USER_PASSWORD_RESET: "重置密码",
    ACTION_USER_DELETE: "硬删用户",
    ACTION_CREDENTIAL_IMPORT: "导入凭证",
    ACTION_CREDENTIAL_DELETE: "删除凭证",
    ACTION_CREDENTIAL_TOGGLE: "启停凭证",
    ACTION_CREDENTIAL_PIN: "指定凭证",
    ACTION_CREDENTIAL_REVIVE: "复活凭证",
    ACTION_CREDENTIAL_SWITCH_ACCOUNT: "切换账号",
}
